services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  medusa-app:
    build: ./
    container_name: medusa-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:medusa@db:5432/medusa-app?ssl_mode=disable
    ports:
      - "9000:9000"
    networks:
      - my-network

  medusa-storefront:
    build: ./medusa-storefront
    container_name: medusa-storefront
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - medusa-app

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge