services:
  medusa-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - medusa-network

  medusa-app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    container_name: medusa-app
    depends_on:
      - medusa-db
    environment:
      DATABASE_URL: postgres://postgres:medusa@medusa-db:5432/medusa-app?ssl_mode=disable
      DB_NAME: medusa-app
      POSTGRES_URL: postgres://postgres:medusa@medusa-db:5432/medusa-app?ssl_mode=disable
    ports:
      - "9000:9000"
    networks:
      - medusa-network

volumes:
  pgdata:

networks:
  medusa-network:
