version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      sh -c "
      apt-get update && apt-get install -y openssl &&
      openssl req -new -x509 -days 365 -nodes -out /var/lib/postgresql/server.crt -keyout /var/lib/postgresql/server.key -subj '/CN=localhost' &&
      chmod 600 /var/lib/postgresql/server.key &&
      echo 'ssl = on' >> /var/lib/postgresql/data/postgresql.conf &&
      echo 'ssl_cert_file = ''/var/lib/postgresql/server.crt''' >> /var/lib/postgresql/data/postgresql.conf &&
      echo 'ssl_key_file = ''/var/lib/postgresql/server.key''' >> /var/lib/postgresql/data/postgresql.conf &&
      postgres
      "

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:medusa@db:5432/medusa-app?sslmode=require
    ports:
      - "9000:9000"
    command: tail -f /dev/null

volumes:
  pgdata: