version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: medusa-app
      DATABASE_URL: postgres://postgres:medusa@db:5432/${DB_NAME}?ssl_mode=disable
      # POSTGRES_URL: postgres://postgres:medusa@db:5432/$DB_NAME?ssl_mode=disable
    ports:
      - "9000:9000"
    command: tail -f /dev/null

volumes:
  pgdata: