services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - medusa-network

  medusa-app:
    build: ./
    container_name: medusa-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:medusa@db:5432/medusa-app?ssl_mode=disable
    ports:
      - "9000:9000"
    networks:
      - medusa-network

volumes:
  pgdata:

networks:
  medusa-network:
